# Generated by Django 5.2.4 on 2025-08-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('nickname', models.CharField(max_length=255, verbose_name='Apelido')),
                ('phone', models.CharField(max_length=20, verbose_name='Número de celular')),
                ('address', models.CharField(max_length=255, verbose_name='Edereço')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('height', models.FloatField(verbose_name='Altura')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
